import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const AccountOrder = sequelize.define(
    "account-order",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },
        ao_nbr:{
            type: Sequelize.STRING,
            unique: true,
        },
        ao_bill: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
        ao_cust: {
            type: Sequelize.STRING,
            references:{
                model: "cm_mstr",
                key: "cm_addr",
            },

        },
    ao_type: Sequelize.STRING, 
    ao_so_nbr: Sequelize.STRING, 
    ao_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_effdate: Sequelize.DATEONLY, 
    ao_date: Sequelize.DATEONLY, 
    ao_cr_terms: Sequelize.STRING, 
    ao_po: Sequelize.STRING, 
    ao_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_disc_date: Sequelize.DATEONLY, 
    ao_due_date: Sequelize.DATEONLY, 
    ao_expt_date: Sequelize.DATEONLY, 
    ao_acct: Sequelize.STRING, 
    ao_cc: Sequelize.STRING, 
    ao_sales_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_xslspsn1: Sequelize.STRING, 
    ao_xslspsn2: Sequelize.STRING, 
    ao_paid_date: Sequelize.DATEONLY, 
    ao_batch: Sequelize.STRING, 
    ao_disc_acct: Sequelize.STRING, 
    ao_disc_cc: Sequelize.STRING, 
    ao_ship: Sequelize.STRING, 
    ao_open: {type: Sequelize.BOOLEAN, defaultValue : true  }, 
    ao_contested: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_check: Sequelize.STRING, 
    ao_cmtindx: Sequelize.INTEGER, 
    ao_user1: Sequelize.STRING, 
    ao_user2: Sequelize.STRING, 
    ao_curr: Sequelize.STRING, 
    ao_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_vao_acct: Sequelize.STRING, 
    ao_vao_cc: Sequelize.STRING, 
    ao_bank: Sequelize.STRING, 
    ao_mrgn_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_entity: Sequelize.STRING, 
    ao_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao__chr01: Sequelize.STRING, 
    ao__chr02: Sequelize.STRING, 
    ao__chr03: Sequelize.STRING, 
    ao__chr04: Sequelize.STRING, 
    ao__chr05: Sequelize.STRING, 
    ao__dte01: Sequelize.DATEONLY, 
    ao__dte02: Sequelize.DATEONLY, 
    ao__dec01: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao__dec02: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao__log01: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_draft: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_ldue_date: Sequelize.DATEONLY, 
    ao_print: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_inv_cr: Sequelize.STRING, 
    ao_fr_terms: Sequelize.STRING, 
    ao_slspsn: Sequelize.STRING, 
    ao_tax_date: Sequelize.DATEONLY, 
    ao_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_tax_env: Sequelize.STRING, 
    ao__qad01: Sequelize.STRING, 
    ao__qad02: Sequelize.STRING, 
    ao__qad03: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_drft_sel: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_coll_mthd: Sequelize.STRING, 
    ao_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_disc_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_base_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_fsm_type: Sequelize.STRING, 
    ao_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_dy_code: Sequelize.STRING, 
    ao_dun_level: Sequelize.INTEGER, 
    ao_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_ex_ratetype: Sequelize.STRING, 
    ao_base_amt_chg: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_base_applied: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_base_comm_amt: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_exru_seq: Sequelize.INTEGER, 
    ao_dd_curr: Sequelize.STRING, 
    ao_dd_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_dd_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  }, 
    ao_dd_exru_seq: Sequelize.INTEGER, 
    ao_app_owner: Sequelize.STRING, 
    ao_sub: Sequelize.STRING, 
    ao_disc_sub: Sequelize.STRING, 
    ao_vao_sub: Sequelize.STRING, 
    ao_prepayment: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_shipfrom: Sequelize.STRING, 
    ao_customer_bank: Sequelize.STRING, 
    ao_draft_disc_date: Sequelize.DATEONLY, 
    ao_recon_date: Sequelize.DATEONLY, 
    ao_status: Sequelize.STRING, 
    ao_customer_initiated: {type: Sequelize.BOOLEAN, defaultValue : false  }, 
    ao_draft_submit_date: Sequelize.DATEONLY, 
    ao_pay_method: Sequelize.STRING, 
    ao_void_date: Sequelize.DATEONLY, 
    ao_domain: Sequelize.STRING,
    oid_ao_mstr: {type: Sequelize.DECIMAL, defaultValue : 0  },
    ...base,
    },
    {
        tableName: "ao_mstr",
    }
)
export default AccountOrder
