import { Container } from "typedi"
import Sequelize from "sequelize"
import base from "./base"

const sequelize = Container.get("sequelize")

const VoucherProformaDetail = sequelize.define(
    "VoucherProformaDetail",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true

        },       
        vdhp_inv_nbr: {
            type: Sequelize.STRING,
            references: {
                model: "vhp_hist",
                key: "vhp_inv_nbr",
            },
        },
        vdhp_line: Sequelize.INTEGER,
        vdhp_part: {
            type: Sequelize.STRING,
            references:{
                model: "pt_mstr",
                key: "pt_part",
            },

        },

        vdhp_tax_code: {
            type: Sequelize.STRING,
            references: {
                model: "tx2_mstr",
                key: "tx2_tax_code",
            },
        },
vdhp_due_date: Sequelize.DATEONLY,
vdhp_per_date: Sequelize.DATEONLY,
vdhp_req_date: Sequelize.DATEONLY,
vdhp_qty_ord:  {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_all: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_pick: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_ship: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_inv: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_loc: Sequelize.STRING,
vdhp_type: Sequelize.STRING,
vdhp_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_std_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_bo_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_acct: Sequelize.STRING,
vdhp_abnormal: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_serial: Sequelize.STRING,
vdhp_desc: Sequelize.STRING,
vdhp_um: Sequelize.STRING,
vdhp_cc: Sequelize.STRING,
vdhp_comment: Sequelize.STRING,
vdhp_lot: Sequelize.STRING,
vdhp_um_conv: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_fa_nbr: Sequelize.STRING,
vdhp_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_project: Sequelize.STRING,
vdhp_cmtindx: Sequelize.INTEGER,
vdhp_custpart: Sequelize.STRING,
vdhp__qad01: Sequelize.INTEGER,
vdhp_status: Sequelize.STRING,
vdhp_xslspsn: Sequelize.STRING,
vdhp_xcomm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_dsc_acct: Sequelize.STRING,
vdhp_dsc_cc: Sequelize.STRING,
vdhp_list_pr: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_user1: Sequelize.STRING,
vdhp_user2: Sequelize.STRING,
vdhp_sob_rev: Sequelize.DATEONLY,
vdhp_sob_std: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_qty_qote: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_consume: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_expire: Sequelize.DATEONLY,
vdhp__qad02: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_taxc: Sequelize.STRING,
vdhp_partial: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_site: Sequelize.STRING,
vdhp_prodline: Sequelize.STRING,
vdhp_tax_in: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_fst_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_pst: {type: Sequelize.BOOLEAN, defaultValue : false  },

vdhp_tax_max: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_curr: Sequelize.STRING,
vdhp_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_curr_rlse_id: Sequelize.STRING,
vdhp_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_contr_id: Sequelize.STRING,
vdhp_pickdate: Sequelize.DATEONLY,
vdhp_confirm: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_cum_qty: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_cum_date: Sequelize.DATEONLY,
vdhp_for: Sequelize.STRING,
vdhp_ref: Sequelize.INTEGER,
vdhp_qty_per: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_item: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_rma_type: Sequelize.STRING,
vdhp_owner: Sequelize.STRING,
vdhp_calc_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_fr_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_slspsn: Sequelize.STRING,
vdhp_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_ord_mult: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_pkg_code: Sequelize.STRING,
vdhp_translt_days: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_fsm_type: Sequelize.STRING,
vdhp_conrep: Sequelize.STRING,
vdhp_sch_data: Sequelize.STRING,
vdhp_sch_mrp: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_rlse_nbr: Sequelize.INTEGER,
vdhp_start_eff: Sequelize.DATEONLY,
vdhp_end_eff: Sequelize.DATEONLY,
vdhp_dock: Sequelize.STRING,
vdhp_pr_list: Sequelize.STRING,
vdhp_translt_hrs: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_out_po: Sequelize.STRING,
vdhp_raw_days: Sequelize.INTEGER,
vdhp_fab_days: Sequelize.INTEGER,
vdhp_tax_usage: Sequelize.STRING,
vdhp_rbkt_days: Sequelize.INTEGER,
vdhp_rbkt_weeks: Sequelize.INTEGER,
vdhp_rbkt_mths: Sequelize.INTEGER,
vdhp_sched_chgd: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_pastdue: Sequelize.STRING,
vdhp_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_fr_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_fr_wt_um: Sequelize.STRING,
vdhp_fr_class: Sequelize.STRING,
vdhp_fr_chg: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_ship: Sequelize.STRING,
vdhp_sa_nbr: Sequelize.STRING,
vdhp_enduser: Sequelize.STRING,
vdhp_isb_loc: Sequelize.STRING,
vdhp_upd_isb: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_isb_ref: Sequelize.INTEGER,
vdhp_auto_ins: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_drp_ref: Sequelize.STRING,
vdhp_tax_env: Sequelize.STRING,
vdhp_crt_int: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_fr_list: Sequelize.STRING,
vdhp_pricing_dt: Sequelize.DATEONLY,
vdhp_act_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_covered_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_fixed_price: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_inv_cost: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_car_load: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_ca_line: Sequelize.INTEGER,
vdhp_qty_cons: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_qty_ret: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_ca_nbr: Sequelize.STRING,
vdhp_qty_pend: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_to_loc: Sequelize.STRING,
vdhp_to_site: Sequelize.STRING,
vdhp_to_ref: Sequelize.STRING,
vdhp_ln_ref: Sequelize.STRING,
vdhp_qty_exch: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_sad_line: Sequelize.INTEGER,
vdhp_warr_start: Sequelize.DATEONLY,
vdhp_mod_userid: Sequelize.STRING,
vdhp_mod_date: Sequelize.DATEONLY,
vdhp_sv_code: Sequelize.STRING,
vdhp_alt_pkg: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_for_serial: Sequelize.STRING,
vdhp_override_lmt: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_bonus: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_btb_type: Sequelize.STRING,
vdhp_btb_po: Sequelize.STRING,
vdhp_btb_pod_line: Sequelize.INTEGER,
vdhp_btb_vend: Sequelize.STRING,
vdhp_exp_del: Sequelize.DATEONLY,
vdhp_dir_all: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_cfg_type: Sequelize.STRING,
vdhp_div: Sequelize.STRING,
vdhp_pl_priority: Sequelize.INTEGER,
vdhp_prig1: Sequelize.STRING,
vdhp_prig2: Sequelize.STRING,
vdhp__qadd04: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_sub: Sequelize.STRING,
vdhp_dsc_sub: Sequelize.STRING,
vdhp_dsc_project: Sequelize.STRING,
vdhp_qty_ivcd: {type: Sequelize.DECIMAL, defaultValue : 0  },
vdhp_cum_time: Sequelize.INTEGER,
vdhp_ship_part: Sequelize.STRING,
vdhp_promise_date: Sequelize.DATEONLY,
vdhp_charge_type: Sequelize.STRING,
vdhp_Proforma_category: Sequelize.STRING,
vdhp_modelyr: Sequelize.STRING,
vdhp_custref: Sequelize.STRING,
vdhp_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_max_aging_days: Sequelize.INTEGER,
vdhp_consign_loc: Sequelize.STRING,
vdhp_intrans_loc: Sequelize.STRING,
vdhp_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_manual_fr_list: {type: Sequelize.BOOLEAN, defaultValue : false  },
vdhp_req_time: Sequelize.STRING,


vdhp_domain: Sequelize.STRING,

...base,
    },
    {
        tableName: "vdhp_det",
    }
)
export default VoucherProformaDetail
