import { Container } from 'typedi';
import Sequelize from 'sequelize';
import base from './base';



const sequelize = Container.get('sequelize');

const VoucherProforma = sequelize.define(
    "voucher-Proforma",
    {
        id: {
            type: Sequelize.INTEGER,
            primaryKey: true,
            autoIncrement: true,
            unique: true,

        },
        vhp_inv_nbr: {
            type: Sequelize.STRING,
            unique: true,
        },
        vhp_vend: {
            type: Sequelize.STRING,
            references:{
                model: "vd_mstr",
                key: "vd_addr",
            },

        },
        
		vhp_po_nbr: Sequelize.STRING,
        vh_ship: Sequelize.STRING,
        vhp_inv_date: Sequelize.DATEONLY,
        vhp_ord_date: Sequelize.DATEONLY,
		vhp_req_date: Sequelize.DATEONLY,
		vhp_due_date: Sequelize.DATEONLY,
		vhp_rmks: Sequelize.STRING,
		vhp_cr_terms: Sequelize.STRING,
		vhp_fob: Sequelize.STRING,
		vhp_shipvia: Sequelize.STRING,
		vhp_stat: Sequelize.STRING,
		vhp_disc_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_tax_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_prepaid: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_to_inv: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_invoiced: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_ar_acct: Sequelize.STRING,
		vhp_ar_cc: Sequelize.STRING,
		
		vhp_ship_date: Sequelize.DATEONLY,
		vhp_taxable: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_user1: Sequelize.STRING,
		vhp_user2: Sequelize.STRING,
		vhp_curr: Sequelize.STRING,
		vhp_ex_rate: {type: Sequelize.DECIMAL, defaultValue : 0  },
        vhp_ex_rate2: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_lang: Sequelize.STRING,
		vhp_type: Sequelize.STRING,
		vhp_conf_date: Sequelize.DATEONLY,
		vhp_rev: Sequelize.INTEGER,
		vhp_bol: Sequelize.STRING,
		vhp_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_tax_amt:  {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_trl1_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_trl1_cd: Sequelize.STRING,
		vhp_trl2_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_trl2_cd: Sequelize.STRING,
		vhp_trl3_amt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_trl3_cd: Sequelize.STRING,
		vhp_weight: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_weight_um: Sequelize.STRING,
		vhp_size: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_size_um: Sequelize.STRING,
		vhp_cartons: Sequelize.INTEGER,
		vhp_site: Sequelize.STRING,
		vhp_pst_id: Sequelize.STRING,
		vhp_cncl_date: Sequelize.DATEONLY,
		vhp_quote: Sequelize.STRING,
		vhp_taxc: Sequelize.STRING,
		vhp_credit: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_inv_cr: Sequelize.STRING,
		vhp_project: Sequelize.STRING,
		vhp_channel: Sequelize.STRING,
		vhp_pst_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_fr_list: Sequelize.STRING,
		vhp_fr_terms: Sequelize.STRING,
		vhp_slspsn: Sequelize.STRING,
		vh_comm_pct: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_inv_mthd: Sequelize.STRING,
		vhp_fix_rate: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_ent_ex: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_print_bl: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_userid: Sequelize.STRING,
		vhp_tax_date: Sequelize.DATEONLY,
        vhp_fsm_type: Sequelize.STRING,
		vhp_conrep: Sequelize.STRING,
		vhp_bank: Sequelize.STRING,
		vhp_tax_env: Sequelize.STRING,
		vhp_sched: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_fr_min_wt: {type: Sequelize.DECIMAL, defaultValue : 0  },
		vhp_pr_list2: Sequelize.STRING,
		vhp_tax_usage: Sequelize.STRING,
		vhp_sa_nbr: Sequelize.STRING,
		vhp_fix_pr: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_sch_mthd: Sequelize.STRING,
		vhp_pricing_dt: Sequelize.DATEONLY,
		vhp_priced_dt: Sequelize.DATEONLY,
		vhp_ca_nbr: Sequelize.STRING,
		vhp_eng_code: Sequelize.STRING,
		vhp_fcg_code: Sequelize.STRING,
		vhp_ship_eng: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_crprlist: Sequelize.STRING,
		vh_incl_iss: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_consignment: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_max_aging_days: Sequelize.INTEGER,
		vhp_consign_loc: Sequelize.STRING,
		vhp_intrans_loc: Sequelize.STRING,
		vhp_auto_replenish: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_revenue: Sequelize.STRING,
		vhp_fsaccr_acct: Sequelize.STRING,
		vhp_fsaccr_sub: Sequelize.STRING,
		vhp_fsaccr_cc: Sequelize.STRING,
		vhp_fsdef_acct: Sequelize.STRING,
		vhp_fsdef_sub: Sequelize.STRING,
		vhp_fsdef_cc: Sequelize.STRING,
		vhp_manual_fr_terms: {type: Sequelize.BOOLEAN, defaultValue : false  },
		vhp_req_time: Sequelize.STRING,
		vhp_domain: Sequelize.STRING,
		...base,
			},
			{
				tableName: "vhp_hist",
			}
		)
export default VoucherProforma;
