import { Router, Request, Response, NextFunction } from 'express';
import { Container } from 'typedi';
import controller from '../controllers/inventory-transaction';
const route = Router();

export default (app: Router) => {
  app.use('/inventory-transactions', route);

  
  route.post('/', controller.create);
  route.get('/findAllissSo', controller.findAllissSo);
  route.get('/:id', controller.findOne);
  route.post('/find', controller.findBy);
  route.put('/:id', controller.update);
  route.delete('/:id', controller.deleteOne);
  route.post('/rct-unp', controller.rctUnp);
  route.post('/rct-unpcab', controller.rctUnpCab);
  route.post('/rct-pocab', controller.rctPoCab);
  route.post('/iss-unp', controller.issUnp);
  route.post('/iss-epi', controller.issEpi);
  route.post('/rct-epi', controller.rctEpi);
  route.post('/iss-tr', controller.issTr);
  route.post('/iss-trv', controller.issTrV);
  route.post('/iss-chl', controller.issChl);
  route.post('/iss-chlref', controller.issChlRef);
  route.post('/Reprint', controller.reprint);
  route.post('/inventoryOfDate', controller.inventoryToDate);
  route.post('/inventoryactivity', controller.inventoryActivity);
  route.post('/inventorybyloc', controller.inventoryByLoc);
  route.post('/inventorybystatus', controller.inventoryByStatus);
  route.post('/inventoryofsecurity', controller.inventoryOfSecurity);
  route.post('/rct-wo', controller.rctWo);
  route.post('/rjct-wo', controller.rjctWo);
  route.post('/iss-wo', controller.issWo);
  route.post('/retiss-wo', controller.retissWo);
  route.post('/updateTr', controller.updateTrans);
  // route.post('/iss-so', controller.issSo);
  route.post('/findtrdate', controller.findtrDate);
  route.post('/findtrdateaddr', controller.findtrDateAddr);
  route.post('/findtrtype', controller.findTrType);
  route.post('/cyc-cnt', controller.cycCnt);
  route.post('/cyc-rcnt', controller.cycRcnt);
  
  route.post('/dayly1', controller.findDayly1);
  route.post('/consoreport', controller.consoReport);
  route.post('/consorange', controller.consoRange);
  route.post('/findByOneinv', controller.findByOneinv);
  route.post('/findinv', controller.findByInv);
  route.post('/findrct', controller.findByRct);
  route.post("/findoa", controller.findBySpec);
  route.get('/', controller.findAll);
  route.post('/findcost', controller.findByCost);
  route.post('/findnbr', controller.findByNbr);
  route.post('/findgroup', controller.findByGroup); 
  route.post('/findgroupepi', controller.findByGroupEpi);
  route.post('/findgroupemp', controller.findByGroupEmp); 
  route.post('/findref', controller.findByRef); 
  route.post('/findrefs', controller.findByRefs); 
  route.post('/findactivity', controller.findByActivity);  
  route.post('/updateprice', controller.updatePrice);
  route.post('/findiss', controller.findByIss);
  route.post('/findepi', controller.findByEpi);
  route.post('/findemploye', controller.findByEmp);
};
